/*
 * ecu_can_definitions.h
 *
 * Created: 6/30/2015 18:01:05
 *  Author: Jimmy Chau
 */ 


#ifndef ECU_CAN_DEFINITIONS_H_
#define ECU_CAN_DEFINITIONS_H_

#include "revolve_can_definitions.h"

#define CAN_ID_INVERTER_VOLTAGE				CANR_FCN_DATA_ID|CANR_GRP_INVERTER_ID|CANR_MODULE_ID0_ID
#define CAN_ID_INVERTER_CURRENT				CANR_FCN_DATA_ID|CANR_GRP_INVERTER_ID|CANR_MODULE_ID1_ID
#define CAN_ID_INVERTER_RPM					CANR_FCN_DATA_ID|CANR_GRP_INVERTER_ID|CANR_MODULE_ID2_ID
#define CAN_ID_INVERTER_ENCODER_POS			CANR_FCN_DATA_ID|CANR_GRP_INVERTER_ID|CANR_MODULE_ID3_ID
#define CAN_ID_INVERTER_INVERTER_TEMP		CANR_FCN_DATA_ID|CANR_GRP_INVERTER_ID|CANR_MODULE_ID4_ID
#define CAN_ID_INVERTER_MOTOR_TEMP			CANR_FCN_DATA_ID|CANR_GRP_INVERTER_ID|CANR_MODULE_ID5_ID
#define CAN_ID_INVERTER_STATE				CANR_FCN_DATA_ID|CANR_GRP_INVERTER_ID|CANR_MODULE_ID6_ID



#define CAN_ID_WHEEL_SPEED_FR				CANR_FCN_DATA_ID|CANR_GRP_SENS_SPEED_ID|CANR_MODULE_ID0_ID 
#define CAN_ID_WHEEL_SPEED_FL				CANR_FCN_DATA_ID|CANR_GRP_SENS_SPEED_ID|CANR_MODULE_ID1_ID 
#define CAN_ID_WHEEL_SPEED_RR				CANR_FCN_DATA_ID|CANR_GRP_SENS_SPEED_ID|CANR_MODULE_ID2_ID 
#define CAN_ID_WHEEL_SPEED_RL				CANR_FCN_DATA_ID|CANR_GRP_SENS_SPEED_ID|CANR_MODULE_ID3_ID 

#define CAN_ID_INVERTER_INVERTER			CANR_FCN_DATA_ID|CANR_GRP_INVERTER_ID|CANR_MODULE_ID7_ID

#define CAN_DASH_ALIVE_ID CANR_FCN_DATA_ID | CANR_GRP_DASH_ID | CANR_MODULE_ID7_ID

#endif /* ECU_CAN_DEFINITIONS_H_ */